kepler3(M₁::Mass, M₂::Mass, P::Time) = uconvert(u"Rsun", cbrt(P^2*u"G"*(M₁ + M₂)/(4π^2)))
kepler3(M₁::Mass, M₂::Mass, a::Length) = uconvert(u"d", 2π*sqrt(a^3/(u"G"*(M₁ + M₂))))
kepler3(s1::Star, s2::Star, x) = kepler3(get_m(s1), get_m(s2), x)
kepler3(s1::Star, s2, x) = kepler3(get_m(s1), s2, x)
kepler3(s1, s2::Star, x) = kepler3(s1, get_m(s2), x)
